# This is a basic workflow to help you get started with Actions

name: KAAKAWW

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  stackhawk-hawkscan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check out Repo!
        uses: actions/checkout@v2
      - name: Build and Run Vulny!
        run: docker compose build && docker compose up -d
      - name: HawkScan
        uses: stackhawk/hawkscan-action@v2.2.0
        continue-on-error: true
        env:
          APP_ENV: GHA
          SARIF_ARTIFACT: true
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
        with:
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
          apiKey: ${{ secrets.HAWK_API_TOKEN }}
          configurationFiles: |
            ./stackhawk.d/stackhawk-custom-params.yml
            ./stackhawk.d/stackhawk-github-pr.yml
      - name: SARIF to CodeQL file
        uses: github/codeql-action/upload-sarif@v3.30.1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: stackhawk.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: StackHawk
      - name: SARIF to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stackhawk-sarif
          path: stackhawk.sarif
          if-no-files-found: warn
          retention-days: 90
          overwrite: true
